site_name: 'Hello World'
site_description: 'Test application to test connectivity with Git.'
nav:
  - "Home": "README.md"
  - "User Guide": "user-guide.md"
  - "Components": '*include ./components/*/mkdocs.yml'
plugins:
  - techdocs-core
  - monorepo
