site_name: 'Hello World'
site_description: 'Test application to test connectivity with Git.'
nav:
  - "Home": "README.md"
  - "User Guide": "user-guide.md"
  - '*include ./components/*/ Components': '!include mkdocs.yml'
plugins:
  - techdocs-core
  - monorepo
