apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test_underscore
  # This is an extra long description
  description: This is a test of Portal connectivity to Github
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team-c
