apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test-underscore
  title: Test Underscore
  description: Everything about testing underscores!
  annotations:
    backstage.io/techdocs-ref: dir:.
    pagerduty.com/integration-key: f9bec7c325134e00c0af1e640eeaf6c8
    github.com/project-slug: The-Outsider-Renaissance/test_underscore
    sentry.io/project-slug: tempo
    jenkins.io/github-folder: powerhome/playbook
    newrelic.com/dashboard-guid: MTc2NTV8VklafERBU0hCT0FSRHw4NzY1OTg
    goharbor.io/repository-slug: library/portal
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  owner: guardians-of-the-galaxy
  domain: testing-domain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-underscore-web
  description: This is a fake web component.
  annotations:
    sentry.io/project-slug: milano
    github.com/project-slug: The-Outsider-Renaissance/test_underscore
    jenkins.io/github-folder: powerhome/nitro-web
    goharbor.io/repository-slug: library/portal
spec:
  type: service
  lifecycle: experimental
  system: test-underscore
  owner: guardians-of-the-galaxy
